(cl:in-package phidgets-msg)
(cl:export '(HEADER-VAL
          HEADER
          INDEX-VAL
          INDEX
          MODE-VAL
          MODE
          DIRECTION-VAL
          DIRECTION
          TARGET_POSITION-VAL
          TARGET_POSITION
          TARGET_VELOCITY-VAL
          TARGET_VELOCITY
          P_GAIN-VAL
          P_GAIN
          I_GAIN-VAL
          I_GAIN
          D_GAIN-VAL
          D_GAIN
          ACC_FF-VAL
          ACC_FF
          FRI_FF-VAL
          FRI_FF
          VEL_FF-VAL
          VEL_FF
          HOLD-VAL
          HOLD
          BIAS-VAL
          BIAS
          ACCEL-VAL
          ACCEL
          TRANS-VAL
          TRANS
          LAG-VAL
          LAG
          MIN-VAL
          MIN
          MAX-VAL
          MAX
          SLEW-VAL
          SLEW
))