/* Auto-generated by genmsg_cpp for file /home/floribot/ros_workspace/ptu_control/msg/PtuSetVelFeedback.msg */
#ifndef PTU_CONTROL_MESSAGE_PTUSETVELFEEDBACK_H
#define PTU_CONTROL_MESSAGE_PTUSETVELFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "sensor_msgs/JointState.h"

namespace ptu_control
{
template <class ContainerAllocator>
struct PtuSetVelFeedback_ {
  typedef PtuSetVelFeedback_<ContainerAllocator> Type;

  PtuSetVelFeedback_()
  : state()
  {
  }

  PtuSetVelFeedback_(const ContainerAllocator& _alloc)
  : state(_alloc)
  {
  }

  typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _state_type;
   ::sensor_msgs::JointState_<ContainerAllocator>  state;


  typedef boost::shared_ptr< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PtuSetVelFeedback
typedef  ::ptu_control::PtuSetVelFeedback_<std::allocator<void> > PtuSetVelFeedback;

typedef boost::shared_ptr< ::ptu_control::PtuSetVelFeedback> PtuSetVelFeedbackPtr;
typedef boost::shared_ptr< ::ptu_control::PtuSetVelFeedback const> PtuSetVelFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ptu_control

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b869e8f6f1d03107da0fd57ef24c9c1d";
  }

  static const char* value(const  ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb869e8f6f1d03107ULL;
  static const uint64_t static_value2 = 0xda0fd57ef24c9c1dULL;
};

template<class ContainerAllocator>
struct DataType< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ptu_control/PtuSetVelFeedback";
  }

  static const char* value(const  ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback\n\
sensor_msgs/JointState state\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/JointState\n\
# This is a message that holds data to describe the state of a set of torque controlled joints. \n\
#\n\
# The state of each joint (revolute or prismatic) is defined by:\n\
#  * the position of the joint (rad or m),\n\
#  * the velocity of the joint (rad/s or m/s) and \n\
#  * the effort that is applied in the joint (Nm or N).\n\
#\n\
# Each joint is uniquely identified by its name\n\
# The header specifies the time at which the joint states were recorded. All the joint states\n\
# in one message have to be recorded at the same time.\n\
#\n\
# This message consists of a multiple arrays, one for each part of the joint state. \n\
# The goal is to make each of the fields optional. When e.g. your joints have no\n\
# effort associated with them, you can leave the effort array empty. \n\
#\n\
# All arrays in this message should have the same size, or be empty.\n\
# This is the only way to uniquely associate the joint name with the correct\n\
# states.\n\
\n\
\n\
Header header\n\
\n\
string[] name\n\
float64[] position\n\
float64[] velocity\n\
float64[] effort\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PtuSetVelFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ptu_control::PtuSetVelFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PTU_CONTROL_MESSAGE_PTUSETVELFEEDBACK_H

