; Auto-generated. Do not edit!


(cl:in-package ptu_control-msg)


;//! \htmlinclude PtuResetGoal.msg.html

(cl:defclass <PtuResetGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PtuResetGoal (<PtuResetGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PtuResetGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PtuResetGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ptu_control-msg:<PtuResetGoal> is deprecated: use ptu_control-msg:PtuResetGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PtuResetGoal>) ostream)
  "Serializes a message object of type '<PtuResetGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PtuResetGoal>) istream)
  "Deserializes a message object of type '<PtuResetGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PtuResetGoal>)))
  "Returns string type for a message object of type '<PtuResetGoal>"
  "ptu_control/PtuResetGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PtuResetGoal)))
  "Returns string type for a message object of type 'PtuResetGoal"
  "ptu_control/PtuResetGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PtuResetGoal>)))
  "Returns md5sum for a message object of type '<PtuResetGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PtuResetGoal)))
  "Returns md5sum for a message object of type 'PtuResetGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PtuResetGoal>)))
  "Returns full string definition for message of type '<PtuResetGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PtuResetGoal)))
  "Returns full string definition for message of type 'PtuResetGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PtuResetGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PtuResetGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PtuResetGoal
))
