; Auto-generated. Do not edit!


(cl:in-package ptu_control-msg)


;//! \htmlinclude PtuSetVelGoal.msg.html

(cl:defclass <PtuSetVelGoal> (roslisp-msg-protocol:ros-message)
  ((pan_vel
    :reader pan_vel
    :initarg :pan_vel
    :type cl:float
    :initform 0.0)
   (tilt_vel
    :reader tilt_vel
    :initarg :tilt_vel
    :type cl:float
    :initform 0.0))
)

(cl:defclass PtuSetVelGoal (<PtuSetVelGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PtuSetVelGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PtuSetVelGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ptu_control-msg:<PtuSetVelGoal> is deprecated: use ptu_control-msg:PtuSetVelGoal instead.")))

(cl:ensure-generic-function 'pan_vel-val :lambda-list '(m))
(cl:defmethod pan_vel-val ((m <PtuSetVelGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ptu_control-msg:pan_vel-val is deprecated.  Use ptu_control-msg:pan_vel instead.")
  (pan_vel m))

(cl:ensure-generic-function 'tilt_vel-val :lambda-list '(m))
(cl:defmethod tilt_vel-val ((m <PtuSetVelGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ptu_control-msg:tilt_vel-val is deprecated.  Use ptu_control-msg:tilt_vel instead.")
  (tilt_vel m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PtuSetVelGoal>) ostream)
  "Serializes a message object of type '<PtuSetVelGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'pan_vel))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'tilt_vel))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PtuSetVelGoal>) istream)
  "Deserializes a message object of type '<PtuSetVelGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pan_vel) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'tilt_vel) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PtuSetVelGoal>)))
  "Returns string type for a message object of type '<PtuSetVelGoal>"
  "ptu_control/PtuSetVelGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PtuSetVelGoal)))
  "Returns string type for a message object of type 'PtuSetVelGoal"
  "ptu_control/PtuSetVelGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PtuSetVelGoal>)))
  "Returns md5sum for a message object of type '<PtuSetVelGoal>"
  "b7cd6f56e9f8de7ca60102f67cb2581f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PtuSetVelGoal)))
  "Returns md5sum for a message object of type 'PtuSetVelGoal"
  "b7cd6f56e9f8de7ca60102f67cb2581f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PtuSetVelGoal>)))
  "Returns full string definition for message of type '<PtuSetVelGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%float32 pan_vel~%float32 tilt_vel~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PtuSetVelGoal)))
  "Returns full string definition for message of type 'PtuSetVelGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%float32 pan_vel~%float32 tilt_vel~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PtuSetVelGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PtuSetVelGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PtuSetVelGoal
    (cl:cons ':pan_vel (pan_vel msg))
    (cl:cons ':tilt_vel (tilt_vel msg))
))
