/* Auto-generated by genmsg_cpp for file /home/floribot/ros_workspace/phidgets/msg/joystick_params.msg */
#ifndef PHIDGETS_MESSAGE_JOYSTICK_PARAMS_H
#define PHIDGETS_MESSAGE_JOYSTICK_PARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace phidgets
{
template <class ContainerAllocator>
struct joystick_params_ {
  typedef joystick_params_<ContainerAllocator> Type;

  joystick_params_()
  : header()
  , axes()
  , buttons()
  {
  }

  joystick_params_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , axes(_alloc)
  , buttons(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _axes_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  axes;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _buttons_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  buttons;


  typedef boost::shared_ptr< ::phidgets::joystick_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::joystick_params_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct joystick_params
typedef  ::phidgets::joystick_params_<std::allocator<void> > joystick_params;

typedef boost::shared_ptr< ::phidgets::joystick_params> joystick_paramsPtr;
typedef boost::shared_ptr< ::phidgets::joystick_params const> joystick_paramsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phidgets::joystick_params_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phidgets::joystick_params_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phidgets

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phidgets::joystick_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phidgets::joystick_params_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phidgets::joystick_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5a9ea5f83505693b71e785041e67a8bb";
  }

  static const char* value(const  ::phidgets::joystick_params_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5a9ea5f83505693bULL;
  static const uint64_t static_value2 = 0x71e785041e67a8bbULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::joystick_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phidgets/joystick_params";
  }

  static const char* value(const  ::phidgets::joystick_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phidgets::joystick_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32[] axes\n\
int32[] buttons\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::phidgets::joystick_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::phidgets::joystick_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::phidgets::joystick_params_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phidgets::joystick_params_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.axes);
    stream.next(m.buttons);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct joystick_params_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::joystick_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phidgets::joystick_params_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "axes[]" << std::endl;
    for (size_t i = 0; i < v.axes.size(); ++i)
    {
      s << indent << "  axes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.axes[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_JOYSTICK_PARAMS_H

