/* Auto-generated by genmsg_cpp for file /home/floribot/ros_workspace/phidgets/msg/led_params.msg */
#ifndef PHIDGETS_MESSAGE_LED_PARAMS_H
#define PHIDGETS_MESSAGE_LED_PARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace phidgets
{
template <class ContainerAllocator>
struct led_params_ {
  typedef led_params_<ContainerAllocator> Type;

  led_params_()
  : header()
  , brightness()
  {
  }

  led_params_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , brightness(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _brightness_type;
  std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  brightness;


  typedef boost::shared_ptr< ::phidgets::led_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::led_params_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct led_params
typedef  ::phidgets::led_params_<std::allocator<void> > led_params;

typedef boost::shared_ptr< ::phidgets::led_params> led_paramsPtr;
typedef boost::shared_ptr< ::phidgets::led_params const> led_paramsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phidgets::led_params_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phidgets::led_params_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phidgets

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phidgets::led_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phidgets::led_params_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phidgets::led_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "96e6783756aededccc7bc0f33d16d7bf";
  }

  static const char* value(const  ::phidgets::led_params_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x96e6783756aededcULL;
  static const uint64_t static_value2 = 0xcc7bc0f33d16d7bfULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::led_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phidgets/led_params";
  }

  static const char* value(const  ::phidgets::led_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phidgets::led_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
byte[] brightness\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::phidgets::led_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::phidgets::led_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::phidgets::led_params_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phidgets::led_params_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.brightness);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct led_params_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::led_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phidgets::led_params_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "brightness[]" << std::endl;
    for (size_t i = 0; i < v.brightness.size(); ++i)
    {
      s << indent << "  brightness[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.brightness[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_LED_PARAMS_H

