/* Auto-generated by genmsg_cpp for file /home/floribot/ros_workspace/phidgets/msg/rfid_params.msg */
#ifndef PHIDGETS_MESSAGE_RFID_PARAMS_H
#define PHIDGETS_MESSAGE_RFID_PARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace phidgets
{
template <class ContainerAllocator>
struct rfid_params_ {
  typedef rfid_params_<ContainerAllocator> Type;

  rfid_params_()
  : header()
  , gained(false)
  , tag()
  {
  }

  rfid_params_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , gained(false)
  , tag(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _gained_type;
  uint8_t gained;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tag_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  tag;


  typedef boost::shared_ptr< ::phidgets::rfid_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::rfid_params_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct rfid_params
typedef  ::phidgets::rfid_params_<std::allocator<void> > rfid_params;

typedef boost::shared_ptr< ::phidgets::rfid_params> rfid_paramsPtr;
typedef boost::shared_ptr< ::phidgets::rfid_params const> rfid_paramsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phidgets::rfid_params_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phidgets::rfid_params_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phidgets

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phidgets::rfid_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phidgets::rfid_params_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phidgets::rfid_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6943b5800eeeaa3d7f682dd30fe8108e";
  }

  static const char* value(const  ::phidgets::rfid_params_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6943b5800eeeaa3dULL;
  static const uint64_t static_value2 = 0x7f682dd30fe8108eULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::rfid_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phidgets/rfid_params";
  }

  static const char* value(const  ::phidgets::rfid_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phidgets::rfid_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool gained\n\
string tag\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::phidgets::rfid_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::phidgets::rfid_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::phidgets::rfid_params_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phidgets::rfid_params_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.gained);
    stream.next(m.tag);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct rfid_params_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::rfid_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phidgets::rfid_params_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gained: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gained);
    s << indent << "tag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tag);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_RFID_PARAMS_H

