/* Auto-generated by genmsg_cpp for file /home/floribot/ros_workspace/phidgets/msg/spatial_params.msg */
#ifndef PHIDGETS_MESSAGE_SPATIAL_PARAMS_H
#define PHIDGETS_MESSAGE_SPATIAL_PARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace phidgets
{
template <class ContainerAllocator>
struct spatial_params_ {
  typedef spatial_params_<ContainerAllocator> Type;

  spatial_params_()
  : header()
  , acceleration()
  , orientation()
  , angular()
  , magnetic()
  , timestamp()
  {
  }

  spatial_params_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , acceleration(_alloc)
  , orientation(_alloc)
  , angular(_alloc)
  , magnetic(_alloc)
  , timestamp(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _acceleration_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  acceleration;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _orientation_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  orientation;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angular_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  angular;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _magnetic_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  magnetic;

  typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _timestamp_type;
  std::vector<double, typename ContainerAllocator::template rebind<double>::other >  timestamp;


  typedef boost::shared_ptr< ::phidgets::spatial_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::spatial_params_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct spatial_params
typedef  ::phidgets::spatial_params_<std::allocator<void> > spatial_params;

typedef boost::shared_ptr< ::phidgets::spatial_params> spatial_paramsPtr;
typedef boost::shared_ptr< ::phidgets::spatial_params const> spatial_paramsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phidgets::spatial_params_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phidgets::spatial_params_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phidgets

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phidgets::spatial_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phidgets::spatial_params_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phidgets::spatial_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0bee8eb74243c85f5ea3cf0935cb1946";
  }

  static const char* value(const  ::phidgets::spatial_params_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0bee8eb74243c85fULL;
  static const uint64_t static_value2 = 0x5ea3cf0935cb1946ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::spatial_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phidgets/spatial_params";
  }

  static const char* value(const  ::phidgets::spatial_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phidgets::spatial_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64[] acceleration\n\
float64[] orientation\n\
float64[] angular\n\
float64[] magnetic\n\
float64[] timestamp\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::phidgets::spatial_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::phidgets::spatial_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::phidgets::spatial_params_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phidgets::spatial_params_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.acceleration);
    stream.next(m.orientation);
    stream.next(m.angular);
    stream.next(m.magnetic);
    stream.next(m.timestamp);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct spatial_params_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::spatial_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phidgets::spatial_params_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration[]" << std::endl;
    for (size_t i = 0; i < v.acceleration.size(); ++i)
    {
      s << indent << "  acceleration[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acceleration[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "angular[]" << std::endl;
    for (size_t i = 0; i < v.angular.size(); ++i)
    {
      s << indent << "  angular[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angular[i]);
    }
    s << indent << "magnetic[]" << std::endl;
    for (size_t i = 0; i < v.magnetic.size(); ++i)
    {
      s << indent << "  magnetic[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.magnetic[i]);
    }
    s << indent << "timestamp[]" << std::endl;
    for (size_t i = 0; i < v.timestamp.size(); ++i)
    {
      s << indent << "  timestamp[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.timestamp[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_SPATIAL_PARAMS_H

