/* Auto-generated by genmsg_cpp for file /home/floribot/ros_workspace/phidgets/msg/stepper_params.msg */
#ifndef PHIDGETS_MESSAGE_STEPPER_PARAMS_H
#define PHIDGETS_MESSAGE_STEPPER_PARAMS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace phidgets
{
template <class ContainerAllocator>
struct stepper_params_ {
  typedef stepper_params_<ContainerAllocator> Type;

  stepper_params_()
  : header()
  , index(0)
  , position(0)
  {
  }

  stepper_params_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , index(0)
  , position(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _index_type;
  int32_t index;

  typedef int64_t _position_type;
  int64_t position;


  typedef boost::shared_ptr< ::phidgets::stepper_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::stepper_params_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct stepper_params
typedef  ::phidgets::stepper_params_<std::allocator<void> > stepper_params;

typedef boost::shared_ptr< ::phidgets::stepper_params> stepper_paramsPtr;
typedef boost::shared_ptr< ::phidgets::stepper_params const> stepper_paramsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::phidgets::stepper_params_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::phidgets::stepper_params_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace phidgets

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::phidgets::stepper_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::phidgets::stepper_params_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::phidgets::stepper_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5cf41f653fc276e6678cd36758f6c957";
  }

  static const char* value(const  ::phidgets::stepper_params_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5cf41f653fc276e6ULL;
  static const uint64_t static_value2 = 0x678cd36758f6c957ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::stepper_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "phidgets/stepper_params";
  }

  static const char* value(const  ::phidgets::stepper_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::phidgets::stepper_params_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32 index\n\
int64 position\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::phidgets::stepper_params_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::phidgets::stepper_params_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::phidgets::stepper_params_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::phidgets::stepper_params_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.index);
    stream.next(m.position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct stepper_params_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::stepper_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::phidgets::stepper_params_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_STEPPER_PARAMS_H

